[package]
name = "exoskeleton"
version = "0.0.1"
authors = ["Sébastien Nadon <sn@sebastiennadon.com>"]

[features]
watch = ["handlebars-iron/watch"]

[dependencies]
iron = "0.3.0"
mount = "0.1.0"
staticfile = "0.2.0"
time = "0.1.35"
router = "0.1.1"
iron-login = "0.4.1"
handlebars-iron = "0.15.1"
